
## Ejecuta servidor en localhost:54321

exeservidor:
	java -Djava.security.policy=servidor.permisos ServidorJuego 54321


## Para el servidor
stopservidor:
	kill -9 $(pidof rmiregistry)


## Desplegar RMI
desplegarrmi:
	rmiregistry &